# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Impostiamo la chiave API come variabile d'ambiente
#       - name: Set up API_KEY as environment variable
#         run: echo "VUE_APP_API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build

#       - name: Deploy to GitHub Pages
#         run: node scripts/gh-pages-deploy.js

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Export Environment Variables
      run: echo "VUE_APP_API_KEY=${{ secrets.API_KEY }}" >> .env


    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VUE_APP_API_KEY: ${{ secrets.API_KEY }}
      run: node scripts/gh-pages-deploy.js

