name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set the environment variable without fs or dotenv
      - name: Set up API_KEY as environment variable
        run: echo "VUE_APP_API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: node scripts/gh-pages-deploy.js
